#pragma config(Motor,  port1,           Claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LiftR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LIftR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Lift2L,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Lift2R,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LiftL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LiftL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           Left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Mobile,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
// Fist Auton




  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  	int Clawopen   = vexRT(Btn8R);
  	int Clawclose  = vexRT(Btn8D);
  	int Mobileup   = vexRT(Btn7L);
  	int MobileDown = vexRT(Btn7D);
  	int Lift2M     = vexRT(Ch2);
  	int Liftdown   = vexRT(Btn5D);
  	int Liftup     = vexRT(Btn5U);
  	int leftstickX;
  	int leftstickY;
  	int deadzone   = 5;


// arcade drive

  	if(abs(vexRT[Ch3]) >deadzone){
			leftstickY = vexRT[Ch3];
		}
		else{
			leftstickY = 0;
		}

		if(abs(vexRT[Ch4]) > deadzone){
			leftstickX = vexRT[Ch4];
		}
		else{
			leftstickX =0 ;
		}

		motor[Left] = leftstickY + leftstickX;
		motor[Right]= leftstickY - leftstickX;
// First lift movement


		if (Liftup == 1){
			motor [LiftR] = 127;
			motor [LiftL] = 127;
			}
		else if (Liftdown  == 1) {
			motor [LiftR] = -127;
			motor [LiftL] = -127;
			}
			else {
				motor[LiftR] = 0;
				motor[LiftL] = 0;
			}

// one stick control for second lift
		if (lift2M >=15){
			motor [Lift2L] = lift2M;
			motor [Lift2R] = lift2M;
		}
		else if (lift2M <=-15){
			motor  [Lift2L] = lift2M;
			motor  [Lift2R] = lift2M;
		}
		else{
			motor [Lift2L] = 0;
			motor [Lift2R] = 0;
		}

		///	Claw Control
		if (Clawopen == 1)
			motor [Claw] = 127;

		else if (Clawclose == 1)
			motor [Claw] = -127;

		else{
			motor [Claw] = 0;
		}
// Mobile goal

		if(Mobileup == 1){
			motor [Mobile] = 127;
		}
		else if (Mobiledown == 1){
			motor [Mobile] = -127;
		}
		else{
			motor [Mobile] = 0;
			motor [Mobile] = 0;
		}
  }
}




    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
