#pragma config(Motor,  port1,           MobileR,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Left,          tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           Right,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          MobileL,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/



task autonomous()
{
  motor [Lift2] = -127;
  wait (1.2);
  motor [Lift2] = 0;
	// flip lift away from mobile goal
  motor [MobileR] = 127;
	motor [MobileL] = 127;
	wait (1.0);
	motor [MobileR] = 0;
	motor [MobileL] = 0;
	// lower mobile goal
  motor [Left] = 127;
  motor [Right] = 127;
  wait (2.9);
  motor [Left] = 0;
  motor [Right] = 0;
  // move forwards towards  goal (mobile goal facing away home)
	motor [MobileR] = -127;
	motor [MobileL] = -127;
	wait (1.0);
	motor [MobileR] = 0;
	motor [MobileL] = 0;
	// raise mobile goal with goal in it
	motor [Lift2] = 127;
  wait (1.2);
  motor [Lift2] = 0;
  // flip lift towards mobile goal, placing preload
  motor [Claw] = -127;
  wait (0.5);
  motor [Claw] = 0;
  // open claw to let go of cone
	motor [Left] = -127;
	motor [Right] = -127;
	wait (3.0);
	motor [Left] = 0;
	motor [Right] = 0;
	// move back to home with cone on mobile goLift2
	motor [Claw] = -127;
	wait (0.5);
	motor [Claw] = 0;
	motor [Lift2] = 127;
	wait (1.5);
	motor [Lift2] = 0;
	// open claw and move arm away from mobile goal
	motor [MobileR] = 127;
	motor [MobileL] = 127;
	// lift mobile goal down
	motor [Left] = 127;
	motor [Right] = 127;
	wait (0.5);
	motor [Left] = 0;
	motor [Right] = 0;

}

	/*

  {
	motor [Lift2] = -127;
	wait (2.0);
	motor [Lift2] = 0;
	// this will make the lift up
	motor [MobileR] = -127;
	motor [MobileL] = -127;
	wait (1.0);
	motor [MobileR] = 0;
	motor [MobileL] = 0;
	// this will make the Mobile goal to go down, and robot is completely open (Transfomation over)
	motor [Left] = 127;
	motor [Right] = 127;
	wait (3.2);
	motor [Left] = 0;
	motor [Right] = 0;
	//this will make so that the robot moves foward towards the mobile goal
	motor [MobileR] = 127;
	motor [MobileL] = 127;
	wait (2.8);
	motor [MobileR] = 0;
	motor [MobileL] = 0;
	//this will make the mobile goal to go up with one moble cone
	motor [Left] = -127;
	motor [Right] = -127;
	wait (4.0);
	motor [Left] = 0;
	motor [Right] = 0;
	//this will make the robot to move back towards the goal
	motor [Right] = -127;
	motor [Left] = 127;
	wait (1.0);
	motor [Right] = 0;
	motor [Left] = 0;
	//this will make the robot to point turn 90 away from the wall
	motor [MobileL] = -127;
	motor [MobileR] = -127;
	wait (1.9);
	motor [MobileL] = 0;
	motor [MobileR] = 0;
  }
	 */




	// ..........................................................................

	// Remove this function call once you have "real" code.

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop( this is to map your bottons)
  while (true)
  {
    //int leftside=vexRT(Ch3);
    //int rightside=vexRT(Ch2);
    int liftup=vexRT(Btn6U);
    int liftdown=vexRT(Btn6D);
    int clawopen=vexRT(Btn8R);
    int clawclose=vexRT(Btn8D);
    int mobileup=vexRT(Btn7L);
    int mobiledown=vexRT(Btn7D);
    int leftY=vexRT(Ch3);
    int leftX=vexRT(Ch4);
    int deadzone = 10; //toleranec for joystick sticking and not returng to zero when released
    int Lift2M=vexRT(Ch2);

  if (abs(vexRT[Ch3]) > deadzone)
  {
    leftY = vexRT[Ch3];
  }
else
  {
    leftY = 0;
  }
  //Get the values of the left (left/right). Prevent small values from moving robot when no stick
  if (abs(vexRT[Ch4]) > deadzone)
  {
    leftX = vexRT[Ch4];
  }
  else
  {
    leftX = 0;
  }

  //ArcadeDrive - Left stick
  motor[Left] = leftY + leftX;

  motor[Right]= leftY - leftX;

  wait1Msec(0.1); //sleep time to allow other tasks to run

    //Drive train
    /*if (leftside >=10)
 {motor [Left] =leftside;
    }
    else if (leftside <=-10)
    {motor [Left] =leftside;
    }
    else
    {motor [Left] =0;
    }

    if (rightside >=10)
    {
      motor [Right] =rightside;
    }
    else if (rightside <=-10)
    {
      motor [Right] =rightside;
    }
    else
    */

   // arcade drive

    {motor [Right] =0;}
    // Lift

    if (liftup == 1) {
      motor [Lift1] = 127;
    }// this is for the lift to go up
    else if (liftdown == 1) {
      motor [Lift1] = -127;
    }//this is lift to go down
    else {
      motor [Lift1] = 0;
    }// this is so the lift doesn't move if there's nothing
    if (Lift2M >=15)
    {motor [Lift2] = Lift2M;
      }
    else if (Lift2M >= -15)
    {motor [lift2] = Lift2M;
      }
    else
    {motor [Lift2]=0;
    if (Lift2M >=15)
    {motor [Lift2] = Lift2M;
      }
    else if (Lift2M >= -15)
    {motor [lift2] = Lift2M;
      }
    else
    {motor [Lift2]=0;
      }
    // Claw control
    if (clawopen == 1)
      motor [Claw] = 127; //opening the claw

    else if (clawclose == 1)
      motor [Claw] = -127; // closing in the claw
    else{
      motor [Claw] = 0;
    }// no claw movement

    if(mobileup == 1){
      motor [MobileR] = 127;
      motor [MobileL] = 127;
    }
    else if (mobiledown == 1){
      motor [MobileR] = -127;
      motor [MobileL] = -127;
    }
    else{
      motor [MobileR] = 0;
      motor [MobileL] = 0;
    }

    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
  }
}
